version: '2'

services:
    php:
        build: ./php-image
        image: php7.4-fpm-nginx
        container_name: php
        ports:
            - "8080:80"
        working_dir: '/code'
        volumes:
            - ./code:/var/www/html
        depends_on: 
            - postgres
        networks:
            - php-network

    postgres:
        image: postgres
        container_name: postgres
        environment: 
            POSTGRES_PASSWORD: 'root123'
        ports:
            - "5433:5432"
        networks: 
            - php-network
    
    # *********** PHP myAdmin container ************
    # pgadmin:
    #     image: dpage/pgadmin4
    #     container_name: pgadmin
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: "joedoe@email.com"
    #         PGADMIN_DEFAULT_PASSWORD: "root123"
    #     ports:
    #         - "8088:80"
    #     depends_on:
    #         - postgres
    #     networks:
    #         - php-network
        

networks:
    php-network:
        driver: bridge
