version: '3'
services:
    nginx:
        container_name: nginx
        image: nginx:1.19.8
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - postgres
        networks:
            - postgres-compose-network            
    php:
        container_name: php
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./app:/app
        networks:
            - postgres-compose-network
    composer:
        container_name: composer
        image: composer:latest
        volumes:
            - ./app:/app
        command: install
        networks:
            - postgres-compose-network
    postgres:
        container_name: postgres
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5434:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
        networks:
            - postgres-compose-network

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "bruno@email.com"
            PGADMIN_DEFAULT_PASSWORD: "postgres"
        ports:
            - "8080:80"
        depends_on:
            - postgres
        networks:
            - postgres-compose-network


networks:
    postgres-compose-network:
        driver: bridge